#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

app->secrets(['Un elefante se balanceaba']);

get '/' => sub {
  my ($c, $args) = @_;
  $c->render(template => 'main/index');
};

get '/new' => sub {
  my ($c, $args) = @_;
  $c->render(template => 'main/new');
};

post '/add' => sub {
  my ($c) = @_;
  my $ammount = $c->param('ammount') // 0;
  my $vendor = $c->param('vendor');
  my $category = $c->param('category'); 
  $c->flash(message => 'Thanks for expensing it');
  $c->stash(ammount => $ammount);
  $c->stash(vendor => $vendor);
  $c->stash(category => $category);
  $c->render(template => 'main/success');
};

app->start;
